# Generated by Django 4.2.1 on 2023-06-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTorneo', models.CharField(max_length=100)),
                ('locacionTorneo', models.CharField(max_length=100)),
                ('teamsParticipando', models.IntegerField()),
                ('premio', models.IntegerField()),
                ('fechaInicio', models.DateField(verbose_name='fecha_inicio')),
                ('fechaTermino', models.DateField(verbose_name='fecha_termino')),
                ('topPlayer', models.CharField(max_length=100)),
                ('teamCampeon', models.CharField(max_length=100)),
            ],
        ),
    ]
