# Generated by Django 4.2.1 on 2023-06-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('link', models.URLField(verbose_name='link')),
                ('time', models.DateTimeField(verbose_name='time')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('mapsPlayed', models.IntegerField(verbose_name='mapsplayed')),
                ('kd', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='kd')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='rating')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id_team', models.AutoField(primary_key=True, serialize=False)),
                ('nameTeam', models.CharField(max_length=50)),
                ('ranking', models.IntegerField(verbose_name='ranking')),
                ('logo', models.ImageField(upload_to='', verbose_name='logo')),
                ('players', models.CharField(max_length=250)),
            ],
        ),
    ]
