# Generated by Django 4.2.1 on 2023-06-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_field', models.CharField(choices=[('Pistols', 'Pistols'), ('Rifles', 'Rifles'), ('SMG', 'SMG'), ('Shotguns', 'Shotguns'), ('Knifes', 'Knifes'), ('Gloves', 'Gloves')], max_length=50)),
                ('nameSkin', models.CharField(max_length=100)),
                ('defWeapon', models.CharField(choices=[('Classified', 'Classified'), ('Restricted', 'Restricted'), ('Mil-spec', 'Mil-spec'), ('Covert', 'Covert'), ('Industrial', 'Industrial'), ('Consumer', 'Consumer')], max_length=50)),
                ('qualityWeapon', models.CharField(choices=[('FN', 'FN'), ('MW', 'MW'), ('FT', 'FT'), ('WW', 'WW'), ('BS', 'BS'), ('ST FN', 'ST FN'), ('ST MW', 'ST MW'), ('ST FT', 'ST FT'), ('ST WW', 'ST WW'), ('ST BS', 'ST BS')], max_length=50)),
                ('containerWeapon', models.CharField(max_length=100)),
                ('collectionsWeapon', models.CharField(max_length=100)),
                ('imagenArma', models.ImageField(upload_to='media')),
                ('precioArma', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='precioarma')),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('link', models.URLField(verbose_name='link')),
                ('time', models.DateTimeField(verbose_name='time')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('mapsPlayed', models.IntegerField(verbose_name='mapsplayed')),
                ('kd', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='kd')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='rating')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id_team', models.AutoField(primary_key=True, serialize=False)),
                ('nameTeam', models.CharField(max_length=50)),
                ('ranking', models.IntegerField(verbose_name='ranking')),
                ('logo', models.ImageField(upload_to='media')),
                ('players', models.CharField(max_length=250)),
            ],
        ),
    ]
