# Generated by Django 4.2.1 on 2023-06-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hltv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='imagenArma',
            field=models.ImageField(upload_to='weapons/'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='logo',
            field=models.ImageField(upload_to='logos/'),
        ),
    ]
