# Generated by Django 4.2.1 on 2023-05-31 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hltv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('link', models.URLField(verbose_name='link')),
                ('time', models.DateTimeField(verbose_name='time')),
            ],
        ),
    ]
